version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        reservations:
          cpus: '0.50'
          memory: 256M

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elastic
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  kafka:
    image: 'bitnami/kafka:3.3.1'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
    volumes:
      - kafkadata:/bitnami/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - elastic

  log-analyses-api:
    image: logalyses/log_prediction_api:latest
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=log_analyses
      - PORT=9090
    ports:
      - "9090:9090"
    depends_on:
      - kafka
    volumes:
      - analyses_api_data:/usr/share/analyses_api
    networks:
      - elastic

  centralized_server:
    build: .
    environment:
      - PORT=8888
      - ELK_HOST=elasticsearch
      - ELK_PORT=9200
      - ELK_PASSWORD=DevelopmentPassword
      - MAIL_HOST=smtp.example.com
      - MAIL_PORT=587
      - MAIL_USERNAME=your-email@example.com
      - MAIL_PASSWORD=your-password
      - MAIL_FROM=your-email@example.com
      - PREDICTOR_API_URL=http://log-analyses-api:9090

    ports:
      - "8888:8888"
      - "3000:3000"           # Dashbord
    depends_on:
      - elasticsearch
      - log-analyses-api
    networks:
      - elastic


volumes:
  esdata:
    driver: local
  kafkadata:
    driver: local
  analyses_api_data:
    driver: local

networks:
  elastic:
    driver: bridge
