version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    deploy:
        resources:
            limits:
                cpus: '0.50'
                memory: 2048M
            reservations:
                cpus: '0.25'
                memory: 256M

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elastic
    deploy:
        resources:
            limits:
                cpus: '0.50'
                memory: 512M
            reservations:
                cpus: '0.25'
                memory: 256M

volumes:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge
